pipeline:
  identifier: Build_jedicraft_jhttp_1755810830698
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: Project4
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1755803134909
        repoName: jedicraft/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: 907949566a9c7239a721e55f5c523d26ac3f2df6a7901ad2b838a0b097286843
                    tags:
                      - new
                    caching: false
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
